/**
 * 실제 Docker 샌드박스에서 에이전트 루프 전체를 검증하는 시나리오.
 * 모델 대신 스크립트를 쓰므로 API 키가 필요 없다. 검증 대상은 모델의 코딩 능력이 아니라
 * "도구 → 파일 변경 → 서비스 재시작 → 준비 판정 → 계약 비교 → 피드백"이 실제로 맞물리는지다.
 *
 *   pnpm e2e:agent
 */
import { cp, mkdir, rm } from 'node:fs/promises';
import { homedir } from 'node:os';
import path from 'node:path';
import { LocalDockerProvider, type Sandbox } from '@b-studio/sandbox';
import { loadProject, type LoadedProject } from '@b-studio/spec';
import { runAgent, ScriptedModelClient, type AgentEvent, type AgentResult, type ScriptedTurn } from '../src/index';

const EXAMPLE = path.resolve(import.meta.dirname, '../../../examples/orders');
const MIGRATIONS = 'api/src/main/resources/db/migration';
const ORDERS_PKG = 'api/src/main/java/com/example/api/orders';

const ENTITY = `package com.example.api.orders;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "orders")
public class CustomerOrder {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "customer_name", nullable = false, length = 100)
    private String customerName;

    protected CustomerOrder() {
    }

    public Long getId() {
        return id;
    }

    public String getCustomerName() {
        return customerNam;
    }
}
`;

const REPOSITORY = `package com.example.api.orders;

import org.springframework.data.jpa.repository.JpaRepository;

interface OrderRepository extends JpaRepository<CustomerOrder, Long> {
}
`;

const CONTROLLER = `package com.example.api.orders;

import java.util.List;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/orders")
class OrderController {

    private final OrderRepository orders;

    OrderController(OrderRepository orders) {
        this.orders = orders;
    }

    @GetMapping
    List<OrderResponse> list() {
        return orders.findAll().stream().map(OrderResponse::from).toList();
    }
}

record OrderResponse(Long id, String customerName) {

    static OrderResponse from(CustomerOrder order) {
        return new OrderResponse(order.getId(), order.getCustomerName());
    }
}
`;

const PAGE = `type Order = { id: number; customerName: string };

export default async function OrdersPage() {
  const response = await fetch(\`\${process.env.API_BASE_URL}/api/orders\`, { cache: "no-store" });
  const orders: Order[] = await response.json();

  return (
    <main className="mx-auto max-w-3xl p-8">
      <h1 className="text-2xl font-semibold">주문</h1>
      <table className="mt-6 w-full text-left text-sm">
        <thead>
          <tr className="border-b">
            <th className="py-2">ID</th>
            <th className="py-2">고객</th>
          </tr>
        </thead>
        <tbody>
          {orders.map((order) => (
            <tr key={order.id} className="border-b">
              <td className="py-2">{order.id}</td>
              <td className="py-2">{order.customerName}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </main>
  );
}
`;

const edit = (file: string, oldText: string, newText: string) => ({ name: 'edit_file', input: { path: file, old_text: oldText, new_text: newText } });
const write = (file: string, content: string) => ({ name: 'write_file', input: { path: file, content } });

interface Scenario {
  name: string;
  request: string;
  allowBreaking?: boolean;
  maxVerifyAttempts?: number;
  turns: ScriptedTurn[];
  expect: (result: AgentResult, events: AgentEvent[], sandbox: Sandbox) => Promise<string[]>;
}

const scenarios: Scenario[] = [
  {
    name: 'A. 주문 목록 API와 화면 (컴파일 에러 → 게이트 실패 → 수정 → 통과)',
    request: '주문 목록 API와 화면을 만들어줘',
    turns: [
      {
        text: '주문 테이블, 엔티티, 조회 API, 화면을 추가합니다.',
        toolCalls: [
          write(`${MIGRATIONS}/V1__create_orders.sql`, "create table orders (\n    id bigint generated by default as identity primary key,\n    customer_name varchar(100) not null\n);\n\ninsert into orders (customer_name) values ('김토스'), ('이스튜디오');\n"),
          write(`${ORDERS_PKG}/CustomerOrder.java`, ENTITY),
          write(`${ORDERS_PKG}/OrderRepository.java`, REPOSITORY),
          write(`${ORDERS_PKG}/OrderController.java`, CONTROLLER),
          write('web/app/orders/page.tsx', PAGE),
        ],
      },
      { text: 'GET /api/orders와 /orders 화면을 추가했습니다.' },
      { toolCalls: [edit(`${ORDERS_PKG}/CustomerOrder.java`, 'return customerNam;', 'return customerName;')] },
      { text: '오타로 인한 컴파일 에러를 고쳤습니다.' },
    ],
    async expect(result, events, sandbox) {
      const gates = events.flatMap((e) => (e.type === 'verify_result' ? [e.report] : []));
      const web = await get(sandbox, 'web', '/orders');
      const api = await get(sandbox, 'api', '/api/orders');
      return [
        check(result.status === 'done', `상태 done (실제: ${result.status})`),
        check(gates.length === 2 && !gates[0]!.ok && gates[1]!.ok, `게이트 [실패, 통과] (실제: ${gates.map((g) => g.ok).join(', ')})`),
        check(gates[0]?.restarted.some((r) => r.service === 'api' && !r.ready && r.logTail?.some((l) => l.includes('cannot find symbol'))) ?? false, '첫 게이트가 api 컴파일 에러 로그를 담음'),
        check(gates[1]?.contracts[0]?.changes.some((c) => c.target === 'GET /api/orders' && !c.breaking) ?? false, '계약에 GET /api/orders 추가'),
        check(api.includes('김토스'), `API 응답에 시드 데이터 (${api.slice(0, 80)})`),
        check(web.includes('김토스'), '/orders 화면에 시드 데이터가 렌더링됨'),
      ];
    },
  },
  {
    name: 'B. 배송 메모 필드 추가 (DB·API·화면 동시 변경, 호환 유지)',
    request: '주문에 배송 메모 필드 추가해줘',
    turns: [
      {
        toolCalls: [
          write(`${MIGRATIONS}/V2__add_order_memo.sql`, "alter table orders add column memo varchar(500);\n\nupdate orders set memo = '문 앞에 놓아주세요' where customer_name = '김토스';\n"),
          edit(`${ORDERS_PKG}/CustomerOrder.java`, '    private String customerName;\n', '    private String customerName;\n\n    @Column(length = 500)\n    private String memo;\n'),
          edit(`${ORDERS_PKG}/CustomerOrder.java`, '        return customerName;\n    }\n', '        return customerName;\n    }\n\n    public String getMemo() {\n        return memo;\n    }\n'),
          edit(`${ORDERS_PKG}/OrderController.java`, 'record OrderResponse(Long id, String customerName) {', 'record OrderResponse(Long id, String customerName, String memo) {'),
          edit(`${ORDERS_PKG}/OrderController.java`, 'order.getCustomerName());', 'order.getCustomerName(), order.getMemo());'),
          edit('web/app/orders/page.tsx', 'customerName: string };', 'customerName: string; memo: string | null };'),
          edit('web/app/orders/page.tsx', '            <th className="py-2">고객</th>\n', '            <th className="py-2">고객</th>\n            <th className="py-2">배송 메모</th>\n'),
          edit('web/app/orders/page.tsx', '              <td className="py-2">{order.customerName}</td>\n', '              <td className="py-2">{order.customerName}</td>\n              <td className="py-2">{order.memo ?? "-"}</td>\n'),
        ],
      },
      { text: 'V2 마이그레이션, 엔티티, 응답, 화면에 배송 메모를 추가했습니다.' },
    ],
    async expect(result, events, sandbox) {
      const gates = events.flatMap((e) => (e.type === 'verify_result' ? [e.report] : []));
      const changes = gates.at(-1)?.contracts[0]?.changes ?? [];
      const web = await get(sandbox, 'web', '/orders');
      return [
        check(result.status === 'done', `상태 done (실제: ${result.status})`),
        check(gates.length === 1 && gates[0]!.ok, '게이트 한 번에 통과'),
        check(changes.length === 1 && changes[0]!.target === 'OrderResponse.memo' && !changes[0]!.breaking, `계약 변경은 OrderResponse.memo 추가 하나 (실제: ${changes.map((c) => c.target).join(', ')})`),
        check(web.includes('문 앞에 놓아주세요'), '/orders 화면에 배송 메모가 렌더링됨'),
      ];
    },
  },
  {
    name: 'C. 요청하지 않은 필드 삭제 (호환 깨짐 → 게이트가 차단)',
    request: '주문 응답을 정리해줘',
    maxVerifyAttempts: 1,
    turns: [
      {
        toolCalls: [
          edit(`${ORDERS_PKG}/OrderController.java`, 'record OrderResponse(Long id, String customerName, String memo) {', 'record OrderResponse(Long id, String customerName) {'),
          edit(`${ORDERS_PKG}/OrderController.java`, 'order.getCustomerName(), order.getMemo());', 'order.getCustomerName());'),
        ],
      },
      { text: '응답에서 쓰지 않는 필드를 정리했습니다.' },
    ],
    async expect(result) {
      const breaking = result.report?.contracts.flatMap((c) => c.changes.filter((change) => change.breaking)) ?? [];
      return [
        check(result.status === 'failed', `상태 failed (실제: ${result.status})`),
        check(result.report?.restarted.every((r) => r.ready) ?? false, 'api 재시작 자체는 성공'),
        check(breaking.some((c) => c.kind === 'property-removed' && c.target === 'OrderResponse.memo'), '호환 깨짐으로 OrderResponse.memo 삭제를 감지'),
      ];
    },
  },
];

async function main(): Promise<number> {
  const workDir = path.join(homedir(), '.cache/b-studio/e2e', `orders-${Date.now()}`);
  await mkdir(path.dirname(workDir), { recursive: true });
  await cp(EXAMPLE, workDir, { recursive: true, filter: (source) => !/[/\\](node_modules|\.next|build|\.gradle)([/\\]|$)/.test(source) });
  log(`작업 복사본: ${workDir}`);

  const project: LoadedProject = await loadProject(workDir);
  const sandbox = await new LocalDockerProvider().create(project);
  const failures: string[] = [];

  try {
    const started = Date.now();
    await sandbox.start();
    log(`샌드박스 준비 (${seconds(started)})`);

    for (const scenario of scenarios) {
      log(`\n▶ ${scenario.name}`);
      const events: AgentEvent[] = [];
      const client = new ScriptedModelClient(scenario.turns);
      const scenarioStarted = Date.now();
      const result = await runAgent({
        request: scenario.request,
        project,
        sandbox,
        client,
        allowBreaking: scenario.allowBreaking,
        maxVerifyAttempts: scenario.maxVerifyAttempts,
        onEvent: (event) => {
          events.push(event);
          if (event.type === 'verify_start') log(`  게이트: ${event.files.length}개 파일 → 재시작·계약 비교`);
          if (event.type === 'verify_result') log(event.text.split('\n').map((line) => `    ${line}`).join('\n'));
        },
      });
      log(`  결과: ${result.status} · ${result.turns}턴 · 게이트 실패 ${result.verifyAttempts}회 · ${seconds(scenarioStarted)}`);

      for (const line of await scenario.expect(result, events, sandbox)) {
        log(`  ${line}`);
        if (line.startsWith('✗')) failures.push(`${scenario.name}: ${line}`);
      }
      if (client.remainingTurns > 0) failures.push(`${scenario.name}: 스크립트 턴 ${client.remainingTurns}개가 남음`);
    }
  } finally {
    await sandbox.destroy();
    if (failures.length === 0) await rm(workDir, { recursive: true, force: true });
  }

  log(failures.length === 0 ? '\n✅ 모든 시나리오 통과' : `\n❌ 실패 ${failures.length}건\n${failures.join('\n')}\n작업 복사본을 남겨 둡니다: ${workDir}`);
  return failures.length === 0 ? 0 : 1;
}

async function get(sandbox: Sandbox, service: string, requestPath: string): Promise<string> {
  const endpoint = await sandbox.endpoint(service);
  const response = await fetch(new URL(requestPath, endpoint.url), { signal: AbortSignal.timeout(120_000) });
  return response.text();
}

function check(condition: boolean, label: string): string {
  return `${condition ? '✓' : '✗'} ${label}`;
}

function seconds(since: number): string {
  return `${((Date.now() - since) / 1000).toFixed(1)}s`;
}

function log(message: string): void {
  console.log(message);
}

main().then(
  (code) => {
    process.exitCode = code;
  },
  (error: unknown) => {
    console.error(error);
    process.exitCode = 1;
  },
);
